/**:
  ros__parameters:
    moveit_servo:
      # General
      publish_period: 0.01
      # Moveit Config
      move_group_name: $(var tf_prefix)manipulator
      planning_frame: $(var tf_prefix)base_link
      ee_frame: $(var tf_prefix)tool0
      is_primary_planning_scene_monitor: false
      # Command in
      command_in_type: "speed_units"
      joint_topic: joint_states
      scale:
        linear: 2.0 # Max Linear Velocity in m/s
        rotational: 5.0 # Max Angular Velocity in rad/s
        joint: 1.00
      # Command out
      command_out_type: trajectory_msgs/JointTrajectory
      command_out_topic: joint_trajectory_controller/joint_trajectory
      publish_joint_positions: true
      publish_joint_velocities: false
      publish_joint_accelerations: false
      use_smoothing: false
